apiVersion: v1
kind: Service
metadata:
  name: read-env-service
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 80 # only mandatory value
      nodePort: 30008
  selector:
    app: mypod-app
